#!/bin/sh

setxkbmap -option caps:escape
setxkbmap -option compose:ralt

# Open X for containers
CONTAINER_XAUTH=/tmp/.Xcontainerauthority
xauth nextract - "$DISPLAY" | sed -e 's/^..../ffff/' | xauth -f "$CONTAINER_XAUTH" nmerge -
chmod 777 $CONTAINER_XAUTH

sleep 1
autorandr -c
