# Commands go through zsh
shell = "zsh -c '{}'"

[[item]]
file = "~/.dotfiles/zsh/theme.zsh"
template = "shell"
rewrite = true
# No hook :(

[[item]]
file = "~/.dotfiles/config/nvim/colors/base16.vim"
template = "vim"
rewrite = true
# No hook :(

[[item]]
file = "~/.dotfiles/config/sway/theme"
template = "sway"
subtemplate = "colors"
hook = "swaymsg reload"
# Swaymsg reload temporarily freezes input, so it's marked as not-light
light = false
rewrite = true

[[item]]
file = "~/.dotfiles/config/i3/config"
template = "i3"
subtemplate = "colors"
hook = "i3-msg reload"
# i3 reload temporarily freezes input, so it's marked as not-light
light = false

[[item]]
file = "~/.dotfiles/config/i3status/config"
template = "i3status"
hook = "i3-msg restart"
# i3 restart might mess up stuff, so it's marked as not-light
light = false

[[item]]
file = "~/.dotfiles/config/alacritty/alacritty.yml"
template = "alacritty"
subtemplate = "default-256"
