# Commands go through zsh
shell = "zsh -c '{}'"

[[item]]
file= "~/.dotfiles/config/zathura/zathurarc"
template = "zathura"

[[item]]
file = "~/.dotfiles/config/sway/theme"
template = "sway"
subtemplate = "colors"
hook = "swaymsg reload"
# Swaymsg reload temporarily freezes input, so it's marked as not-light
light = false
rewrite = true

[[item]]
file = "~/.dotfiles/config/i3/config"
template = "i3"
subtemplate = "colors"
hook = "i3-msg reload"
# i3 reload temporarily freezes input, so it's marked as not-light
light = false

[[item]]
file = "~/.dotfiles/config/i3status-rust/config.toml"
template = "i3status-rust"
hook = "i3-msg restart || swaymsg restart"
# i3/sway restart might mess up stuff, so it's marked as not-light
light = false

[[item]]
file = "~/.dotfiles/config/i3status/config"
template = "i3status"
hook = "i3-msg restart || swaymsg restart"
# i3/sway restart might mess up stuff, so it's marked as not-light
light = false

[[item]]
file = "~/.dotfiles/config/dunst/dunstrc"
template = "dunst"
hook = "killall dunst"

[[item]]
file = "~/.config/rofi/themes/colors.rasi"
template = "rofi"
subtemplate = "colors"
rewrite = true

[[item]]
file = "~/.dotfiles/Xresources"
template = "xresources"
subtemplate = "default-256"
# What if the configuration doesn't support '#' comments? Just change them!
start= "! Start flavours"
end = "! End flavours"
hook = "xrb -merge ~/.Xresources"
