# Start flavours
# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Atelier Cave by Bram de Haan (http://atelierbramdehaan.nl)

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#19171c"
idle_fg = "#8b8792"
info_bg = "#398bc6"
info_fg = "#19171c"
good_bg = "#2a9292"
good_fg = "#19171c"
warning_bg = "#a06e3b"
warning_fg = "#19171c"
critical_bg = "#be4678"
critical_fg = "#19171c"
# The rest of the theme settings are left at default.
# End flavours

[icons]
icons = "material-nf"

[[block]]
block = "net"
format = "{ssid} {signal_strength} {ip} {speed_up;K*b} {speed_down;K*b}"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "temperature"
interval = 10

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "memory"
format = "$icon $mem_total_used_percents.eng(w:2)"
format_alt = "$icon_swap $swap_used_percents.eng(w:2)"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "$icon root: $available.eng(w:2)"

[[block]]
block = "sound"

[[block]]
block = "hueshift"
hue_shifter = "redshift"
click_temp = 3500

[[block]]
block = "backlight"
minimum = 15
maximum = 100
cycle = [100, 50, 15]

[[block]]
block = "time"
format = "%a %d.%m.%y %T"
