# Start flavours
# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Dracula by Mike Barkmin (http://github.com/mikebarkmin) based on Dracula Theme (http://github.com/dracula)

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#282936"
idle_fg = "#e9e9f4"
info_bg = "#a1efe4"
info_fg = "#282936"
good_bg = "#ebff87"
good_fg = "#282936"
warning_bg = "#00f769"
warning_fg = "#282936"
critical_bg = "#ea51b2"
critical_fg = "#282936"
# The rest of the theme settings are left at default.
# End flavours

[icons]
name = "material-nf"


[[block]]
block = "net"
format = "{ssid} {signal_strength} {ip} {speed_up;K*b} {speed_down;K*b}"
hide_inactive = true
interval = 5

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "temperature"
interval = 10

[[block]]
block = "cpu"
interval = 1
format = "{utilization} @ {frequency}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0


[[block]]
block = "sound"

[[block]]
block = "hueshift"
# hue_shifter = "redshift"
step = 50
click_temp = 3500

# [[block]]
# block = "notify"

[[block]]
block = "time"
interval = 5
format = "%a %d.%m.%y %T"
